# Generated by Django 3.2.9 on 2021-11-04 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_rename_prority_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.date(2021, 11, 4)),
        ),
    ]
